(function($){'use strict';var roberto_window=$(window);roberto_window.on('load',function(){$('#preloader').fadeOut('1000',function(){$(this).remove();});});if($.fn.classyNav){$('#robertoNav').classyNav();}
$(".single-project-slide").on("mouseenter",function(){$(".single-project-slide").removeClass("active");$(this).addClass("active");});if($.fn.owlCarousel){var welcomeSlider=$('.welcome-slides');welcomeSlider.owlCarousel({items:1,loop:true,autoplay:true,smartSpeed:1000,nav:true})
welcomeSlider.on('translate.owl.carousel',function(){var layer=$("[data-animation]");layer.each(function(){var anim_name=$(this).data('animation');$(this).removeClass('animated '+anim_name).css('opacity','0');});});$("[data-delay]").each(function(){var anim_del=$(this).data('delay');$(this).css('animation-delay',anim_del);});$("[data-duration]").each(function(){var anim_dur=$(this).data('duration');$(this).css('animation-duration',anim_dur);});welcomeSlider.on('translated.owl.carousel',function(){var layer=welcomeSlider.find('.owl-item.active').find("[data-animation]");layer.each(function(){var anim_name=$(this).data('animation');$(this).addClass('animated '+anim_name).css('opacity','1');});});function welcomeSlide(){$('.owl-item').removeClass('prev next');var currentSlide=$('.welcome-slides .owl-item.active');currentSlide.next('.owl-item').addClass('next');currentSlide.prev('.owl-item').addClass('prev');var nextSlideImg=$('.owl-item.next').find('.single-welcome-slide').attr('data-img-url');var prevSlideImg=$('.owl-item.prev').find('.single-welcome-slide').attr('data-img-url');$('.owl-nav .owl-prev').css({background:'url('+prevSlideImg+')'});$('.owl-nav .owl-next').css({background:'url('+nextSlideImg+')'});}
welcomeSlide();welcomeSlider.on('translated.owl.carousel',function(){welcomeSlide();});}
if($.fn.owlCarousel){var projectSlide=$('.projects-slides');projectSlide.owlCarousel({items:5,margin:0,loop:true,autoplay:true,smartSpeed:1500,dots:true,responsive:{0:{items:1},768:{items:2},992:{items:3},1500:{items:4}}});}
if($.fn.owlCarousel){var testiThumbSlide=$('.testimonial-thumbnail');testiThumbSlide.owlCarousel({items:1,margin:0,loop:true,autoplay:true,smartSpeed:500});}
if($.fn.owlCarousel){var testiSlides=$('.testimonial-slides');testiSlides.owlCarousel({items:1,margin:0,loop:true,autoplay:true,smartSpeed:1000});}
if($.fn.owlCarousel){var roomSlides=$('.rooms-slides');roomSlides.owlCarousel({items:1,margin:0,loop:true,autoplay:true,smartSpeed:1500,nav:true,navText:[('<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Previous'),('Next <i class="fa fa-long-arrow-right" aria-hidden="true"></i>')]});roomSlides.on('translate.owl.carousel',function(){var layer=$("[data-animation]");layer.each(function(){var anim_name=$(this).data('animation');$(this).removeClass('animated '+anim_name).css('opacity','0');});});$("[data-delay]").each(function(){var anim_del=$(this).data('delay');$(this).css('animation-delay',anim_del);});$("[data-duration]").each(function(){var anim_dur=$(this).data('duration');$(this).css('animation-duration',anim_dur);});roomSlides.on('translated.owl.carousel',function(){var layer=roomSlides.find('.owl-item.active').find("[data-animation]");layer.each(function(){var anim_name=$(this).data('animation');$(this).addClass('animated '+anim_name).css('opacity','1');});});}
$('.search-btn').on('click',function(){$('.search-form').toggleClass('search-form-active');})
if($.fn.magnificPopup){$('.video-play-btn').magnificPopup({type:'iframe'});}
if($.fn.tooltip){$('[data-toggle="tooltip"]').tooltip();}
if(roberto_window.width()>767){new WOW().init();}
if($.fn.jarallax){$('.jarallax').jarallax({speed:0.5});}
if($.fn.scrollUp){roberto_window.scrollUp({scrollSpeed:1500,scrollText:'<i class="arrow_carrot-up"</i>'});}
if($.fn.counterUp){$('.counter').counterUp({delay:15,time:1500});}
$('a[href="#"]').on('click',function($){$.preventDefault();});if($.fn.countdown){$("#clock").countdown("2021/10/10",function(event){$(this).html(event.strftime("<div>%D <span>Days</span></div> <div>%H <span>Hours</span></div> <div>%M <span>Mins</span></div> <div>%S <span>Sec</span></div>"));});}
if($.fn.countdown){$('select').niceSelect();}
if($.fn.datepicker){$('.input-daterange').datepicker({format:"dd/mm/yy",multidate:true,keyboardNavigation:false,forceParse:false,daysOfWeekHighlighted:"0,1,2,3,4,5,6",todayHighlight:true});}
$('.slider-range-price').each(function(){var min=jQuery(this).data('min');var max=jQuery(this).data('max');var unit=jQuery(this).data('unit');var value_min=jQuery(this).data('value-min');var value_max=jQuery(this).data('value-max');var label_result=jQuery(this).data('label-result');var t=$(this);$(this).slider({range:true,min:min,max:max,values:[value_min,value_max],slide:function(event,ui){var result=label_result+" "+unit+ui.values[0]+' - '+unit+ui.values[1];console.log(t);t.closest('.slider-range').find('.range-price').html(result);}});})})(jQuery);